[package]
name    = "swiedowski_engine"
version = "1.0.0"
edition = "2021"

[workspace]
members = [
	"bindings",
	"math",
]

[dependencies]
binds  = {path = "bindings"}
math   = {path = "math"}
sdl2   = "0.35"
