[package]
name    = "vulkan"
version = "1.0.0"
edition = "2021"
build   = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.0"
